# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"__version__": "00_core.ipynb",
         "__repo__": "00_core.ipynb",
         "ID_CODE": "01_codes.ipynb",
         "REG_CODE": "01_codes.ipynb",
         "REG_VAL_LEN": "01_codes.ipynb",
         "CMD_CATALOG": "01_codes.ipynb",
         "CMD_CODE": "01_codes.ipynb",
         "CMD_NAME": "01_codes.ipynb",
         "CMD_VAL_LEN": "01_codes.ipynb",
         "REP_CLI_CATALOG": "01_codes.ipynb",
         "stats_struct": "01_codes.ipynb"}

modules = ["core.py",
           "codes.py"]

doc_url = "https://durapensa.github.io/CircuitPython_pico_pi_common/"

git_url = "https://github.com/durapensa/CircuitPython_pico_pi_common/tree/main/"

def custom_doc_links(name): return None
