# AUTOGENERATED! DO NOT EDIT! File to edit: 99_code.ipynb (unless otherwise specified).

__all__ = ['controller']

# Cell

from CircuitPython_pico_pi_controller.CircuitPython_pico_pi_controller import *
from CircuitPython_pico_pi_controller.reports import *

# Cell

controller = PPController(save=False,bosmang=0x13)

While True:
    controller.png_ppds()
    time.sleep(1)