# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['__version__', '__repo__']

# Cell
# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
# SPDX-FileCopyrightText: Copyright (c) 2021 Durapensa
#
# SPDX-License-Identifier: MIT
"""
`pico_pi_common`
================================================================================

A library shared by Pico Pi Controller libraries


* Author(s): Durapensa

Implementation Notes
--------------------

**Hardware:**

**Software and Dependencies:**

* Adafruit CircuitPython firmware for the supported boards:
  https://github.com/adafruit/circuitpython/releases
"""

# imports

__version__ = "0.0.0-auto.0"
__repo__ = "https://github.com/durapensa/CircuitPython_pico_pi_common.git"