# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"__version__": "00_core.ipynb",
         "__repo__": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://durapensa.github.io/CircuitPython_pico_pi_controller/"

git_url = "https://github.com/durapensa/CircuitPython_pico_pi_controller/tree/main/"

def custom_doc_links(name): return None
